### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by flaviomor** [dasGringuen/assetto_corsa_gym#5] opened 2024-09-26 11:47 UTC

**Comment by flaviomor** [comment] 2024-09-26 11:49
Here is the error when I try to use the code to download data:

PS C:\Users\Admin\assetto_corsa_gym> python .\download_track_car.py
Fetching 16 files:   0%|                                                                                                                                                         | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Admin\assetto_corsa_gym\download_track_car.py", line 16, in <module>
    snapshot_download(repo_id="dasgringuen/assettoCorsaGym",
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\_snapshot_download.py", line 290, in snapshot_download        
    thread_map(
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\Admin\anaconda3\envs\p309\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\Users\Admin\anaconda3\envs\p309\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\Admin\anaconda3\envs\p309\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Admin\anaconda3\envs\p309\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\_snapshot_download.py", line 264, in _inner_hf_hub_download   
    return hf_hub_download(
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\file_download.py", line 1212, in hf_hub_download
    return _hf_hub_download_to_local_dir(
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\file_download.py", line 1508, in _hf_hub_download_to_local_dir
    _download_to_tmp_and_move(
  File "C:\Users\Admin\anaconda3\envs\p309\lib\site-packages\huggingface_hub\file_download.py", line 1903, in _download_to_tmp_and_move    
    with incomplete_path.open("ab") as f:
  File "C:\Users\Admin\anaconda3\envs\p309\lib\pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\Admin\anaconda3\envs\p309\lib\pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'AssettoCorsaGymDataSet2\\.cache\\huggingface\\download\\data_sets\\ks_barcelona-layout_gp\\bmw_z4_gt3\\20240221_AR\\laps\\ks_barcelona_&_bmw_z4_
gt3_&_adrianremonda_&_stint_2.ld.184b947366633808749b530934eb037003d7101e8a4f4dddd5c33c20ceec2714.incomplete'

Code:

from huggingface_hub import snapshot_download

# track = "indi"
# track = "indianapolis_sp"
track = "ks_barcelona-layout_gp"

car = "bmw_z4_gt3"
# car = "dallara_f317"
# car = "ks_mazda_miata"

# ids = "20240329_HC"
ids = "20240221_AR"


snapshot_download(repo_id="dasgringuen/assettoCorsaGym",
                  repo_type="dataset",
                  local_dir="AssettoCorsaGymDataSet2",
                  allow_patterns="data_sets/" + track + "/" + car + "/" + ids +"/*")

**Comment by flaviomor** [comment] 2024-09-26 12:05
![Capture](https://github.com/user-attachments/assets/0b0dd694-c695-4a49-8b31-4db00fb61b72)

**Comment by flaviomor** [comment] 2024-09-26 12:06
Unsafe files ?

**Comment by dasGringuen** [comment] 2024-09-26 15:24
Hmm, no idea why they marked them as unsafe. It's probably a false positive. I'll take a look. We've been using these files for months now.

**Comment by flaviomor** [comment] 2024-09-26 15:27
Ok but still not able to download with your code... see comments above. Thx.

**Comment by dasGringuen** [comment] 2024-09-26 16:43
The problem is that our pickle files are importing numpy:

Detected Pickle imports (4)

"numpy.core.multiarray.scalar",
"numpy.core.multiarray._reconstruct",
"numpy.dtype",
"numpy.ndarray"

Hugging Face does not like this for security reasons. I will need to convert them to another format, like Parquet.

**Comment by flaviomor** [comment] 2024-09-27 05:49
Ok, thx but converting all the 120GB will take a lot of time... I need the data asap please. Appreciated.

**Comment by dasGringuen** [comment] 2024-09-27 10:10
I can share the pickles with you via Dropbox until I fix this

**Comment by flaviomor** [comment] 2024-09-27 11:08
Yes, with pleasure... Thx!

**Comment by flaviomor** [comment] 2024-09-30 06:30
Download data without any issues through the above provided links.... THX!

**Comment by dasGringuen** [comment] 2024-10-07 18:29
You can download the dataset by cloning the repository:

```git clone https://huggingface.co/datasets/dasgringuen/assettoCorsaGym```

Delete the `.git` directory to free up space.

Thanks for reporting this! I’m closing the issue.

**Closed by dasGringuen** 2024-10-07 18:29 UTC
