### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 

### ISSUE THREAD

**Issue by LostThinker** [dasGringuen/assetto_corsa_gym#2] opened 2024-07-27 14:51 UTC
Hi,

I am encountering an issue when trying to configure Assetto Corsa and run the show static info block in test_client.ipynb. Specifically, I get the following error: "ConnectionRefusedError: [WinError 10061] The connection could not be established because the target computer actively refused it."

I followed the tutorial step-by-step, configured Assetto Corsa, and selected the same car and track as specified in the config.yaml. Additionally, I started a race before running the code. The error suggests that the server might not be started.

Could you please provide more detailed instructions on how to properly run the demo?

Thank you!

**Comment by dasGringuen** [comment] 2024-07-29 10:41
Hi,

The context manager should be installed. Then, you can enable the Python console, and you should get a log similar to the one below. Can you share the log?

![image](https://github.com/user-attachments/assets/3039a640-083f-4e98-83f7-32d1f44d763b)

**Comment by LostThinker** [comment] 2024-08-14 15:00
Hi,
Thank you for your reply! I checked the output of the Python console, as shown in the following image. I tried to find out why but failed. 
![image](https://github.com/user-attachments/assets/b2adea85-0cf0-4502-9780-99035eabf425)

**Comment by dasGringuen** [comment] 2024-08-14 15:15
It seems that you have an issue with the Python distribution. Did you copy the Dlls and Lib from ```assetto_corsa_gym\assetto-corsa-autonomous-racing-plugin\windows-libs``` to the ```Steam\steamapps\common\assettocorsa\system\x64``` folder?


Follow this [README](https://github.com/dasGringuen/assetto_corsa_gym/blob/main/assetto_corsa_gym/assetto-corsa-autonomous-racing-plugin/windows-libs/README.txt).

It should be something like:

![image](https://github.com/user-attachments/assets/a2da3f3c-5422-4c57-a1a0-d7e525546340)

![image](https://github.com/user-attachments/assets/85101de2-d33c-4028-b574-d0982aaff6d1)

**Comment by LostThinker** [comment] 2024-08-18 13:18
I'm sure I did everything according to the readme, but the error still exists. I don't know much about the python plugin for Assetto Corsa, but it looks like it calls python33.zip as an interpreter. I'm wondering if this interpreter has anything to do with the local python environment?

**Comment by dasGringuen** [comment] 2024-08-19 12:52
Maybe you have a default Python distribution that is conflicting with the one provided by AC. Could you add a few lines to sensor_par.py to print that and share it here? It should be as follows:
```
import sys
import time
import traceback
import datetime
import ac
import acsys

# setup logger
import ac_logger
ac_logger.setup_logger()

import logging
logger = logging.getLogger(__name__)
logger.info("Starting sensors_par...")

import platform
logger.info("Python version: {}".format(sys.version))
logger.info("Python path: {}".format(sys.executable))
logger.info("Architecture: {}".format(platform.architecture()))

```
I'm getting this:
![image](https://github.com/user-attachments/assets/75d9531c-1fb4-4bb1-a744-e51c99e53f2c)

**Comment by dasGringuen** [comment] 2024-08-19 13:23
I see where the problem is. You will need to update sensor_par.py [here](https://github.com/dasGringuen/assetto_corsa_gym/blob/main/assetto_corsa_gym/assetto-corsa-autonomous-racing-plugin/plugins/sensors_par/sensors_par.py#L40) with your path. This happened because you have AC installed on the F drive.

Anyway, I pushed a fix. It should automatically detect the path now
Thanks for reporting this.

**Closed** 2024-09-08 09:27 UTC
